#!/bin/zsh
set -euo pipefail
cd "$(dirname "$0")/.."
{
  echo "// Generated by scripts/embed-sprite.sh from Assets/knight-rgsdev-v3.png. Do not edit."
  echo "// Knight by rgsdev, CC BY-SA 4.0 — see Assets/LICENSE-knight.md"
  printf 'let knightSheetBase64 = "'
  base64 -i Assets/knight-rgsdev-v3.png | tr -d '\n'
  echo '"'
} > Sources/Keeper/KnightSheet.swift
echo "wrote Sources/Keeper/KnightSheet.swift"
